export const PUSH_TEST_OVERVIEW = "TEST_PUSH_OVERVIEW";
export const UPDATE_APPLICATION = "TEST_UPDATE_APPLICATION";
export const UPDATE_TEST_ATTEMPT_SUBSET = "TEST_UPDATE_APPLICATION_SUBSET";
export const PUSH_QUALITATIVE_ANAL = "PUSH_QUALITATIVE_ANAL";
export const PUSH_PERSONALITY_ANAL = "PUSH_PERSONALITY_ANAL";
